# ==========================================
# CONFIGURACIÓN DE EMERGENCIA TOTAL (SIN COMPONENTES)
# ==========================================

spring.data.jpa.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
                             org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
                             org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
                             org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

spring.main.allow-bean-definition-overriding=true

server.port=10000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB