# ==========================================
# CONFIGURACIÓN PARA DESPLIEGUE EN NUBE (SIN DB)
# ==========================================

# 1. Apagar repositorios y desactivar autoconfiguración de BD
spring.data.jpa.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# 2. Configuración de archivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 3. Fechas
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

# 4. Puerto de Render
server.port=10000