# ==========================================
# CONFIGURACIÓN DE EMERGENCIA TOTAL PARA RENDER
# ==========================================

# 1. Forzar a Spring a ignorar todas las clases que busquen base de datos
spring.profiles.active=modo_vacio_render

# 2. Apagar la autoconfiguración de JPA para que no busque credenciales
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
                             org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
                             org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
                             org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# 3. Puerto requerido por Render
server.port=10000